apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdwc-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sdwc-api
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: sdwc-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sdwc-web
                port:
                  number: 80
